#import "@preview/lilaq:0.5.0" as lq

#set page(background: image("assets/frontpage.jpg"))
#v(209pt)
#h(105pt)
Jakob Haverkamp
#h(155pt)
5932110

#h(105pt)
Milan Fark
#h(186pt)
5900383

#set page(background: [])

#import "@local/ufr-sheet-universal:0.1.0": conf

#show: doc => conf(
  doc,
  subject: "Electronics Laboratory",
  date: "11.01.2025",
  prof: "Prof. Dr. Hans Zappe",
  semester: "WS 25/26",
  title: "Lab 4 - MOSFETs",
  header_start: 2,
  name: "jh1444, mf643",
  left_header: [Jakob Haverkamp \ Milan Fark \ jh1444, #h(5pt)mf643],
)
#counter(page).update(1)
#set text(
  lang: "en",
  size: 11pt,
)

#set figure(numbering: "1")
#show ref: set text(fill: blue)


= 4.2 Non-inverting amplifier

== 4.2.1 Simulation

=== Introduction

In this section, we simulated a non-inverting amplifier circuit shown in @4.3.1.circuit.

=== Circuit Diagrams:

#figure(
  caption: [LTSpice _non-inverting amplifier_ circuit diagram#footnote[We changed `AC 5` to `AC 1` (we originally tried to do 15 mV as in the real measurement, but with 1 V we got very similar values to 15 mV so we decided on that.)]],
)[
  #image("assets/4.2.1.circuit.jpg", width: 45%)
] <4.2.1.circuit>

=== Plots:

#include "1.2.plot_sim.typ"

=== Text Questions:

With $R_1$ in the circuit, it reaches $0$ dB amplification at $f approx 3184$ kHz and has $$

=== Conclusion:

== 4.2.2. Measurement

=== Introduction


=== Circuit Diagrams:

#figure(caption: [Schematic of the _non-inverting amplifier_ circuit])[
  #image("assets/4.2.2.circuit.jpg", width: 43%)
] <4.2.2.circuit>

=== Plots:

#include "1.2.plot_real.typ"

=== Text Questions:

=== Conclusion

= 4.3 Voltage-to-current converter

== 4.3.1 Simulation

=== Introduction

=== Circuit Diagrams:

#figure(caption: [LTSpice _voltage-to-current converter_ circuit diagram])[
  #image("assets/4.3.1.circuit.jpg", width: 49%)
] <4.3.1.circuit>

=== Plots:

#include "1.3.plot_sim.typ"

=== Text Questions:

=== Conclusion:

== 4.3.2. Measurement

=== Introduction


=== Circuit Diagrams:

#figure(caption: [Schematic of the _voltage-to-current converter_ circuit])[
  #image("assets/4.3.2.circuit.jpg", width: 57%)
] <fig5>

=== Plots:

#include "1.3.plot_real.typ"

=== Text Questions:

The current through the LED was measured as the voltage drop over $R_89 = 470 Omega$ at `Pin1` of `JP15` and calculated by $I_D = V_(P i n 1) / R_89$.

The voltage drop of the LED was calculated by taking the difference of the voltage between `Pin1` and `Pin2`

$V_(s(m a x)) approx 8.1$ V

=== Conclusion

= 4.4 Transimpedance Amplifier

== 4.4.1 Simulation

=== Introduction
In this section the goal is to simulate a transimpedance amplifier, but used a current source in place of a photodiode.
=== Circuit Diagrams:

#figure(caption: [LTSpice _transimpedance amplifier_ circuit diagram])[
  #image("assets/4.4.1.circuit.jpg", width: 55%)
] <fig1>

=== Plots:

#include "1.4.plot_sim.typ"

=== Text Questions:
As the transimpedance factor is $V_(o u t) / I_(p d)$ and they are linearly dependant, as shown in @fig12, the transimpedance factor is roughly -1. The factor is mainly dependant on the resist $R_f$. 
=== Conclusion:

== 4.4.2. Measurement

=== Introduction
In this section we use a transimpedance amplifier to calculate the current generated by a photodiode by means of output voltage.

=== Circuit Diagrams:

#figure(caption: [Schematic of the _transimpedance amplifier_ circuit])[
  #image("assets/4.4.2.circuit.jpg", width: 47%)
] <fig5>

=== Plots:

#include "1.4.plot_real.typ"

=== Text Questions:
(c) to estimate the current over D16, we use the relation $U= - R * I$ where R is R88 as it is inside the feedback loop of the amplifier circuit. This leads to $I = -U/R$

(d) The current flows in the opposite direction of the input current, because the photodiode is in the same direction as the red LED but used to generate the current.

(f) The output voltage of the transimpedance amplifier is the input voltage $V_s / 1*10^6$ because the resist R88 is 1M$Omega$. this is shown in the data, as $V_o$ is the same as $I_(p d)$ just different by a factor of 1M. The data for $V_s$ > 0 is explained by the means of current generation. As the current is generated via a photodiode, which in turn is powered by a LED. The LED only turns on for currents greater than the forward voltage of the diode. This leads to the circuit of the transimpedance amplifier only being powered while the LED is on making measurement below $V_(f w d)$ pointless.
=== Conclusion
The measurement data showed the characteristics of the transimpedance amplifier to transform current into voltage. It also showcased the direct relation of the two, as well as the ability of a LED to function as a photodiode.
